#!/usr/bin/env python3

import sys
import os
import subprocess
import pickle

class ProcMan:
	def __init__(self):
		self.processes = {}

		self.load()

	def load(self):
		try:
			f = open(".procmandb", "rb")
		except:
			pass
		else:
			self.processes = pickle.load(f)

	def save(self):
		try:
			f = open(".procmandb", "wb")
		except:
			pass
		else:
			pickle.dump(self.processes, f)

	def start(self, argv):
		x = subprocess.Popen(argv)
		print("launched {0} => {1}".format(str(argv), x.pid))
		self.processes[x.pid] = argv
		self.save()

	def status(self):
		for pid in self.processes:
			alive = os.path.isdir("/proc/{0}".format(pid))
			try:
				pgid = os.getpgid(pid)
			except:
				pgid = -1
			status = "pgid={0} alive={1}".format(pgid, alive)
			print("check {0} => {1}: {2}".format(pid, self.processes[pid], status))

	def parseargs(self):
		if len(sys.argv) >= 2:
			if sys.argv[1] == "start":
				if len(sys.argv) >= 3:
					self.start(sys.argv[2:])
				else:
					return 1
			elif sys.argv[1] == "stop":
				pass
			elif sys.argv[1] == "status":
				self.status()
			else:
				return 1
		else:
			print("procman start|stop|status <app/unit>")
			return 1

pm = ProcMan()
sys.exit(pm.parseargs())
